import { getRequestHeaders } from "@tanstack/react-start/server";
import { and, desc, eq, inArray, sql } from "drizzle-orm";
import guessWords from "@/data/catalan-guess-words.json";
import allWords from "@/data/catalan-words.json";
import type { Word } from "@/data/types";
import { user } from "@/db/auth-schema";
import {
	dailyPuzzles,
	legacyImportedResults,
	puzzleWordClues,
	userPuzzleEvents,
	userPuzzleProgress,
} from "@/db/schema";
import { auth } from "@/lib/auth";
import { generateAndStoreCluesForPuzzle } from "@/lib/clue-generator.server";
import { getClueInbox } from "@/lib/clue-request.server";
import { generateDailyCrosswordForSeed } from "@/lib/crossword-generator";
import { db } from "@/lib/db";
import {
	getLeaderboard,
	leaderboardDisplayName,
	mergeAnonLeaderboardForUser,
	recordProgress as recordLeaderboardProgress,
	updateLeaderboardProfile,
	userParticipantId,
} from "@/lib/leaderboard.server";
import {
	captureServerEvent,
	captureServerException,
} from "@/lib/observability-server";
import { hashText, openAnswerCapsule } from "@/lib/puzzle-crypto";
import {
	dateKeyToSeed,
	getNextRolloverAt,
	getTodayDateKey,
	getYesterdayDateKey,
} from "@/lib/puzzle-dates";
import {
	buildNormalizedDictionary,
	getValidNormalizedGuessesForLetters,
} from "@/lib/puzzle-dictionary";
import {
	buildWordFrequencyLookup,
	computeDifficultyForNormalizedWords,
	type PuzzleDifficulty,
} from "@/lib/puzzle-difficulty";
import {
	buildSyncedProgressState,
	createEmptyProgressState,
	getCompatibleProgress,
	mergeProgressStates,
} from "@/lib/puzzle-progress";
import {
	buildPuzzleSnapshots,
	ensureHintCapsulesCoverGrid,
	hydratePublicSnapshotWordMetadata,
	toPuzzlePreview,
} from "@/lib/puzzle-snapshot";
import { calculateHistoryStats } from "@/lib/puzzle-streaks";
import {
	collectAckedEventIds,
	filterSyncablePuzzleEvents,
	hasLeaderboardScoreDelta,
} from "@/lib/puzzle-sync";
import {
	type AnonymousImportPayload,
	type DailyPuzzlePrivateWord,
	type DailyPuzzlePublic,
	HISTORY_PAGE_SIZE,
	type HistoryEntriesPage,
	type HistoryStats,
	type HistorySummaryEntry,
	type PuzzleClientEvent,
	type PuzzleProgressState,
	type SessionUser,
} from "@/lib/puzzle-types";
import {
	normalizeDisplayNameInput,
	resolveAvatarImage,
	resolveDisplayName,
} from "@/lib/user-profile";

export const PUZZLE_ALGORITHM_VERSION = "3";

// Puzzles are generated only from the common-word dictionary (frequency-floored),
// while guesses are validated against the wider name-only dictionary so players
// get credit for any corpus-attested word, however rare. See
// scripts/download-catalan-dictionary.ts.
const serverWords = allWords as Word[];
const normalizedServerWords = buildNormalizedDictionary(guessWords);

let cachedDictionaryVersion: Promise<string> | null = null;
let cachedFrequencyLookup: Map<string, number> | null = null;
const validNormalizedGuessesCache = new Map<string, string[]>();
const inProgressGenerations = new Map<string, Promise<void>>();
const cluesGenerationStarted = new Set<string>();

function getFrequencyLookup() {
	if (!cachedFrequencyLookup) {
		cachedFrequencyLookup = buildWordFrequencyLookup(serverWords);
	}
	return cachedFrequencyLookup;
}

// Lazily fills in a stored puzzle's difficulty when it predates the difficulty
// column (or was generated by an older build). New puzzles already get it at
// generation time, so this is a no-op for them; for older rows it computes the
// rating from the saved snapshot's words and persists it on first read, so the
// indicator appears without needing the backfill script.
async function ensurePuzzleRowDifficulty(
	row: typeof dailyPuzzles.$inferSelect,
): Promise<typeof dailyPuzzles.$inferSelect> {
	if (row.difficulty != null) {
		return row;
	}

	const difficulty = computeDifficultyForNormalizedWords(
		row.privateSnapshotJson.wordSlots.map((slot) => slot.normalizedWord),
		getFrequencyLookup(),
	);
	if (difficulty == null) {
		return row;
	}

	const publicSnapshotJson = { ...row.publicSnapshotJson, difficulty };
	await db
		.update(dailyPuzzles)
		.set({ difficulty, publicSnapshotJson })
		.where(eq(dailyPuzzles.id, row.id));

	return { ...row, difficulty, publicSnapshotJson };
}

// Fire-and-forget AI clue generation for a freshly created puzzle. Never blocks
// or fails puzzle creation: a missing API key or API error only means clues are
// absent (players fall back to letter hints).
function triggerCluesGeneration(
	puzzleId: string,
	wordSlots: DailyPuzzlePrivateWord[],
): void {
	if (cluesGenerationStarted.has(puzzleId)) return;
	cluesGenerationStarted.add(puzzleId);

	void generateAndStoreCluesForPuzzle({ puzzleId, wordSlots })
		.catch((error: unknown) => {
			console.error(
				`[puzzle-service] Clue generation failed for puzzle ${puzzleId}:`,
				error,
			);
			captureServerException(error, {
				properties: { puzzle_id: puzzleId, scope: "clue_generation" },
			});
		})
		.finally(() => {
			cluesGenerationStarted.delete(puzzleId);
		});
}

function toSessionUser(
	sessionData: Awaited<ReturnType<typeof getAuthSession>>,
	profile?: {
		displayName: string | null;
		useGoogleAvatar: boolean;
	} | null,
): SessionUser {
	if (!sessionData) {
		return null;
	}
	const userRecord = {
		name: sessionData.user.name,
		displayName: profile?.displayName ?? null,
		image: sessionData.user.image,
		useGoogleAvatar: profile?.useGoogleAvatar ?? true,
	};
	return {
		id: sessionData.user.id,
		name: resolveDisplayName(userRecord),
		displayName: profile?.displayName ?? null,
		email: sessionData.user.email,
		image: resolveAvatarImage(userRecord),
		googleImage: sessionData.user.image ?? null,
		useGoogleAvatar: profile?.useGoogleAvatar ?? true,
	};
}

async function getUserProfileFields(userId: string) {
	const profiles = await db
		.select({
			displayName: user.displayName,
			useGoogleAvatar: user.useGoogleAvatar,
		})
		.from(user)
		.where(eq(user.id, userId))
		.limit(1);
	return profiles[0] ?? null;
}

async function toEnrichedSessionUser(
	sessionData: Awaited<ReturnType<typeof getAuthSession>>,
): Promise<SessionUser> {
	if (!sessionData) {
		return null;
	}
	const profile = await getUserProfileFields(sessionData.user.id);
	return toSessionUser(sessionData, profile);
}

// Narrows a stored difficulty (a nullable integer column or snapshot value) to
// the 1-3 star union, dropping anything out of range to null.
function toPuzzleDifficulty(
	value: number | null | undefined,
): PuzzleDifficulty | null {
	return value === 1 || value === 2 || value === 3 ? value : null;
}

function serializeProgressRow(
	row: typeof userPuzzleProgress.$inferSelect,
): PuzzleProgressState {
	return {
		puzzleId: row.puzzleId,
		guessHashes: row.guessHashes,
		guessedWordIds: row.guessedWordIds,
		revealedWordTokens: row.revealedWordTokens,
		hintedCells: row.hintedCells,
		clueWordIds: row.clueWordIds,
		hintsUsed: row.hintsUsed,
		guessCount: row.guessCount,
		bonusWordsFound: row.bonusWordsFound,
		shuffledLetters: row.shuffledLetters,
		completedAt: row.completedAt?.toISOString() ?? null,
		lastSyncedAt: row.lastSyncedAt.toISOString(),
	};
}

function getStoredEventAt(row: typeof userPuzzleEvents.$inferSelect): string {
	const eventAt =
		typeof row.payload === "object" &&
		row.payload !== null &&
		"_eventAt" in row.payload &&
		typeof row.payload._eventAt === "string"
			? row.payload._eventAt
			: null;

	return eventAt ?? row.createdAt.toISOString();
}

function toPuzzleClientEvent(
	row: typeof userPuzzleEvents.$inferSelect,
): PuzzleClientEvent | null {
	const at = getStoredEventAt(row);

	switch (row.type) {
		case "guess_added":
		case "hint_used":
		case "text_hint_requested":
		case "bonus_clue_revealed":
		case "letters_shuffled":
		case "progress_reset":
			return {
				id: row.clientEventId,
				at,
				type: row.type,
				payload: row.payload,
			} as PuzzleClientEvent;
		default:
			return null;
	}
}

async function getDictionaryVersion() {
	if (!cachedDictionaryVersion) {
		cachedDictionaryVersion = hashText(
			JSON.stringify(
				serverWords.map((word) => ({
					name: word.name,
					areatematica: word.areatematica,
					frequency: word.frequency,
				})),
			),
		);
	}

	return cachedDictionaryVersion;
}

function getDailyValidNormalizedGuesses(letters: string[]) {
	const cacheKey = [...letters].sort().join("");
	const cachedGuesses = validNormalizedGuessesCache.get(cacheKey);

	if (cachedGuesses) {
		return cachedGuesses;
	}

	const validGuesses = getValidNormalizedGuessesForLetters(
		normalizedServerWords,
		letters,
	);
	validNormalizedGuessesCache.set(cacheKey, validGuesses);
	return validGuesses;
}

export async function getAuthSession() {
	const headers = new Headers(getRequestHeaders());
	return auth.api.getSession({
		headers,
	});
}

export async function publishLeaderboardForUser(input: {
	dateKey: string;
	userId: string;
	wordsFound: number;
	totalWords: number;
	freeCluesUsed: number;
	tryCount: number;
	completedAt: string | null;
	previousWordsFound: number;
	previousCompletedAt: string | null;
}) {
	try {
		const profiles = await db
			.select({
				name: user.name,
				displayName: user.displayName,
				image: user.image,
				useGoogleAvatar: user.useGoogleAvatar,
			})
			.from(user)
			.where(eq(user.id, input.userId))
			.limit(1);
		const profile = profiles[0];
		if (!profile) return;

		const displayName = leaderboardDisplayName(resolveDisplayName(profile));
		const avatarImage = resolveAvatarImage(profile);

		// Total clues = the free clues spent plus every clue a friend delivered
		// (one inbox entry per word).
		const friendClues = (await getClueInbox(input.userId, input.dateKey))
			.length;

		await recordLeaderboardProgress({
			dateKey: input.dateKey,
			participantId: userParticipantId(input.userId),
			kind: "user",
			name: displayName,
			image: avatarImage,
			wordsFound: input.wordsFound,
			totalWords: input.totalWords,
			clueCount: input.freeCluesUsed + friendClues,
			tryCount: input.tryCount,
			completedAt: input.completedAt,
			previousWordsFound: input.previousWordsFound,
			previousCompletedAt: input.previousCompletedAt,
		});
	} catch (error) {
		console.warn("[leaderboard] publish for user failed", error);
	}
}

export async function checkDailyPuzzleExists(
	dateKey = getTodayDateKey(),
): Promise<boolean> {
	const existing = await db.query.dailyPuzzles.findFirst({
		where: eq(dailyPuzzles.dateKey, dateKey),
		columns: { id: true },
	});
	return existing != null;
}

// Lightweight lookup for UI that only needs today's rating (leaderboard header).
// Does not generate a puzzle: if today's row isn't there yet, callers omit the
// indicator. The column is authoritative; the snapshot covers older rows.
export async function getDailyPuzzleDifficulty(
	dateKey = getTodayDateKey(),
): Promise<PuzzleDifficulty | null> {
	const existing = await db.query.dailyPuzzles.findFirst({
		where: eq(dailyPuzzles.dateKey, dateKey),
		columns: { difficulty: true, publicSnapshotJson: true },
	});
	if (!existing) {
		return null;
	}
	return toPuzzleDifficulty(
		existing.difficulty ?? existing.publicSnapshotJson.difficulty,
	);
}

// Reads a stored puzzle without ever creating one. Every request-driven path
// goes through this: generation is expensive (a placement search over the whole
// dictionary) and it spends Anthropic credits on clues, so it may not be
// reachable by naming a date in a request. See triggerDailyPuzzleGeneration for
// the one on-demand exception.
export async function readDailyPuzzleRow(dateKey = getTodayDateKey()) {
	const existing = await db.query.dailyPuzzles.findFirst({
		where: eq(dailyPuzzles.dateKey, dateKey),
	});

	return existing ? ensurePuzzleRowDifficulty(existing) : null;
}

export class DailyPuzzleNotFoundError extends Error {
	constructor(dateKey: string) {
		super(`No puzzle stored for ${dateKey}`);
		this.name = "DailyPuzzleNotFoundError";
	}
}

// On-demand generation, reachable from a page load. Restricted to today so a
// caller can't mint puzzles for arbitrary dates: tomorrow's is pre-generated by
// the pre-generator container an hour before rollover (see scripts/pre-generate.sh),
// past days are filled by the backfill script, and both call
// ensureDailyPuzzleSnapshot directly. Today is the only date a request may still
// need to bootstrap (a cold start, or a missed pre-generation), and generating it
// discloses nothing a player can't see.
export function triggerDailyPuzzleGeneration(
	dateKey = getTodayDateKey(),
): void {
	if (dateKey !== getTodayDateKey()) {
		console.warn(
			`[puzzle-service] Refusing on-demand generation for ${dateKey}: only today may be generated on demand`,
		);
		return;
	}

	if (inProgressGenerations.has(dateKey)) return;

	const promise = ensureDailyPuzzleSnapshot(dateKey)
		.then(() => {})
		.catch((err: unknown) => {
			console.error(
				`[puzzle-service] Puzzle generation failed for ${dateKey}:`,
				err,
			);
		})
		.finally(() => {
			inProgressGenerations.delete(dateKey);
		});

	inProgressGenerations.set(dateKey, promise);
}

export async function ensureDailyPuzzleSnapshot(dateKey = getTodayDateKey()) {
	const existing = await db.query.dailyPuzzles.findFirst({
		where: eq(dailyPuzzles.dateKey, dateKey),
	});

	if (existing) {
		return ensurePuzzleRowDifficulty(existing);
	}

	const seed = dateKeyToSeed(dateKey);
	const generated = generateDailyCrosswordForSeed(serverWords, seed);

	if (!generated) {
		throw new Error(`Failed to generate puzzle for ${dateKey}`);
	}

	const puzzleId = crypto.randomUUID();
	const { publicSnapshot, privateSnapshot } = await buildPuzzleSnapshots({
		puzzleId,
		dateKey,
		seed,
		crossword: generated.crossword,
		letters: generated.letters,
		initialShuffledLetters: generated.shuffledLetters,
		algorithmVersion: PUZZLE_ALGORITHM_VERSION,
	});

	const inserted = await db
		.insert(dailyPuzzles)
		.values({
			id: puzzleId,
			dateKey,
			seed,
			algorithmVersion: PUZZLE_ALGORITHM_VERSION,
			dictionaryVersion: await getDictionaryVersion(),
			wordCount: privateSnapshot.wordSlots.length,
			difficulty: publicSnapshot.difficulty ?? null,
			publicSnapshotJson: publicSnapshot,
			privateSnapshotJson: privateSnapshot,
		})
		.onConflictDoNothing({
			target: dailyPuzzles.dateKey,
		})
		.returning();

	if (inserted[0]) {
		captureServerEvent({
			event: "daily_puzzle_generated",
			properties: {
				date_key: dateKey,
				puzzle_id: inserted[0].id,
				seed,
				word_count: privateSnapshot.wordSlots.length,
			},
		});
		triggerCluesGeneration(inserted[0].id, privateSnapshot.wordSlots);
		return inserted[0];
	}

	const conflictRow = await db.query.dailyPuzzles.findFirst({
		where: eq(dailyPuzzles.dateKey, dateKey),
	});

	if (!conflictRow) {
		throw new Error(`Failed to persist puzzle for ${dateKey}`);
	}

	return ensurePuzzleRowDifficulty(conflictRow);
}

export async function getDailyPuzzlePublicData(dateKey = getTodayDateKey()) {
	const puzzle = await readDailyPuzzleRow(dateKey);
	if (!puzzle) {
		throw new DailyPuzzleNotFoundError(dateKey);
	}

	const sessionData = await getAuthSession();
	const historyEntries = sessionData
		? await getHistoryEntriesForUser(sessionData.user.id)
		: null;
	const publicSnapshot = hydratePublicSnapshotWordMetadata({
		publicSnapshot: puzzle.publicSnapshotJson,
		privateSnapshot: puzzle.privateSnapshotJson,
	});
	const hintCapsules = await ensureHintCapsulesCoverGrid({
		puzzleId: publicSnapshot.id,
		seed: publicSnapshot.seed,
		gridLetters: puzzle.privateSnapshotJson.gridLetters,
		existingHintCapsules: publicSnapshot.hintCapsules,
	});

	return {
		historyEntries,
		puzzle: {
			...publicSnapshot,
			hintCapsules,
			validNormalizedGuesses: getDailyValidNormalizedGuesses(
				publicSnapshot.letters,
			),
			// The column is authoritative (kept in sync by generation and backfill);
			// fall back to the snapshot JSON for rows persisted before the column.
			difficulty: toPuzzleDifficulty(
				puzzle.difficulty ?? publicSnapshot.difficulty,
			),
		},
		rolloverAt: getNextRolloverAt().toISOString(),
		sessionUser: await toEnrichedSessionUser(sessionData),
	};
}

export async function getSessionUserData() {
	return toEnrichedSessionUser(await getAuthSession());
}

export async function getUserPuzzleProgressData(
	puzzleId: string,
	userId: string,
) {
	const row = await db.query.userPuzzleProgress.findFirst({
		where: and(
			eq(userPuzzleProgress.puzzleId, puzzleId),
			eq(userPuzzleProgress.userId, userId),
		),
	});

	return row ? serializeProgressRow(row) : null;
}

// Returns the clue text for the requested word ids, keyed by wordId. Only
// words the player has unlocked (via a spent hint or by finding them) are
// returned. Pending text_hint_requested events count too so a fetch can race
// ahead of progress sync without failing.
export async function getWordCluesData(options: {
	puzzleId: string;
	wordIds: number[];
	userId: string | null;
}): Promise<Record<number, string>> {
	const { puzzleId, userId, wordIds } = options;
	if (wordIds.length === 0) {
		return {};
	}

	const puzzleRow = await db.query.dailyPuzzles.findFirst({
		where: eq(dailyPuzzles.id, puzzleId),
		columns: { publicSnapshotJson: true },
	});
	if (!puzzleRow) {
		return {};
	}

	const validWordIds = new Set(
		puzzleRow.publicSnapshotJson.wordSlots.map((slot) => slot.id),
	);

	const authorizedWordIds = userId
		? await getAuthorizedClueWordIds({
				puzzleId,
				userId,
			})
		: null;

	const allowedWordIds = wordIds.filter((wordId) => {
		if (!validWordIds.has(wordId)) {
			return false;
		}
		if (authorizedWordIds) {
			return authorizedWordIds.has(wordId);
		}
		return true;
	});

	if (allowedWordIds.length === 0) {
		return {};
	}

	const rows = await db.query.puzzleWordClues.findMany({
		where: and(
			eq(puzzleWordClues.puzzleId, puzzleId),
			inArray(puzzleWordClues.wordId, allowedWordIds),
		),
	});

	const cluesByWordId: Record<number, string> = {};
	for (const row of rows) {
		cluesByWordId[row.wordId] = row.sonnetClue;
	}
	return cluesByWordId;
}

async function getAuthorizedClueWordIds(options: {
	puzzleId: string;
	userId: string | null;
}): Promise<Set<number>> {
	const authorized = new Set<number>();
	if (!options.userId) {
		return authorized;
	}

	const progress = await getUserPuzzleProgressData(
		options.puzzleId,
		options.userId,
	);
	if (progress) {
		for (const wordId of progress.clueWordIds) {
			authorized.add(wordId);
		}
		for (const wordId of progress.guessedWordIds) {
			authorized.add(wordId);
		}
	}

	const pendingHintEvents = await db.query.userPuzzleEvents.findMany({
		where: and(
			eq(userPuzzleEvents.userId, options.userId),
			eq(userPuzzleEvents.puzzleId, options.puzzleId),
			eq(userPuzzleEvents.type, "text_hint_requested"),
		),
		columns: { payload: true },
	});

	for (const row of pendingHintEvents) {
		const wordId =
			typeof row.payload === "object" &&
			row.payload !== null &&
			"wordId" in row.payload &&
			typeof row.payload.wordId === "number"
				? row.payload.wordId
				: null;
		if (wordId != null) {
			authorized.add(wordId);
		}
	}

	const matchedGuessEvents = await db.query.userPuzzleEvents.findMany({
		where: and(
			eq(userPuzzleEvents.userId, options.userId),
			eq(userPuzzleEvents.puzzleId, options.puzzleId),
			eq(userPuzzleEvents.type, "guess_added"),
		),
		columns: { payload: true },
	});

	for (const row of matchedGuessEvents) {
		const wordId =
			typeof row.payload === "object" &&
			row.payload !== null &&
			"matchedWordId" in row.payload &&
			typeof row.payload.matchedWordId === "number"
				? row.payload.matchedWordId
				: null;
		if (wordId != null) {
			authorized.add(wordId);
		}
	}

	return authorized;
}

export async function syncPuzzleEventsForUser(options: {
	puzzleId: string;
	userId: string;
	deviceId: string;
	events: PuzzleClientEvent[];
}) {
	const { deviceId, events, puzzleId, userId } = options;
	const puzzleRow = await db.query.dailyPuzzles.findFirst({
		where: eq(dailyPuzzles.id, puzzleId),
	});

	if (!puzzleRow) {
		throw new Error("Puzzle not found");
	}

	const privateSnapshot = puzzleRow.privateSnapshotJson;
	const publicSnapshot = puzzleRow.publicSnapshotJson;
	const eventIds = events.map((event) => event.id);
	const existingEvents =
		eventIds.length === 0
			? []
			: await db.query.userPuzzleEvents.findMany({
					where: and(
						eq(userPuzzleEvents.userId, userId),
						eq(userPuzzleEvents.puzzleId, puzzleId),
						eq(userPuzzleEvents.deviceId, deviceId),
						inArray(userPuzzleEvents.clientEventId, eventIds),
					),
				});

	const existingEventIdSet = new Set(
		existingEvents.map((event) => event.clientEventId),
	);

	const existingProgress = await getUserPuzzleProgressData(puzzleId, userId);

	const { diagnostics, filteredEvents } = await filterSyncablePuzzleEvents({
		events,
		existingEventIds: existingEventIdSet,
		publicSnapshot,
		privateSnapshot,
		existingHintState: existingProgress
			? {
					hintsUsed: existingProgress.hintsUsed,
					hintedCells: existingProgress.hintedCells,
					clueWordIds: existingProgress.clueWordIds,
				}
			: undefined,
	});

	await Promise.all(
		filteredEvents.map((event) =>
			db
				.insert(userPuzzleEvents)
				.values({
					id: crypto.randomUUID(),
					userId,
					puzzleId,
					deviceId,
					clientEventId: event.id,
					type: event.type,
					payload: {
						...event.payload,
						_eventAt: event.at,
					},
				})
				.onConflictDoNothing(),
		),
	);

	let historicalEvents: PuzzleClientEvent[] = [];

	if (!existingProgress) {
		const allEvents = await db.query.userPuzzleEvents.findMany({
			where: and(
				eq(userPuzzleEvents.userId, userId),
				eq(userPuzzleEvents.puzzleId, puzzleId),
			),
		});

		historicalEvents = allEvents
			.map((row) => toPuzzleClientEvent(row))
			.filter((event): event is PuzzleClientEvent => event !== null);
	}

	const nextProgress = buildSyncedProgressState({
		existingProgress,
		historicalEvents,
		incomingEvents: filteredEvents,
		initialProgress: createEmptyProgressState(publicSnapshot),
		totalWords: privateSnapshot.wordSlots.length,
	});

	await db
		.insert(userPuzzleProgress)
		.values({
			id: `${userId}:${puzzleId}`,
			userId,
			puzzleId,
			guessHashes: nextProgress.guessHashes,
			guessedWordIds: nextProgress.guessedWordIds,
			revealedWordTokens: nextProgress.revealedWordTokens,
			hintedCells: nextProgress.hintedCells,
			clueWordIds: nextProgress.clueWordIds,
			hintsUsed: nextProgress.hintsUsed,
			guessCount: nextProgress.guessCount,
			bonusWordsFound: nextProgress.bonusWordsFound,
			shuffledLetters: nextProgress.shuffledLetters,
			completedAt: nextProgress.completedAt
				? new Date(nextProgress.completedAt)
				: null,
			lastSyncedAt: new Date(),
		})
		.onConflictDoUpdate({
			target: userPuzzleProgress.id,
			set: {
				guessHashes: nextProgress.guessHashes,
				guessedWordIds: nextProgress.guessedWordIds,
				revealedWordTokens: nextProgress.revealedWordTokens,
				hintedCells: nextProgress.hintedCells,
				clueWordIds: nextProgress.clueWordIds,
				hintsUsed: nextProgress.hintsUsed,
				guessCount: nextProgress.guessCount,
				bonusWordsFound: nextProgress.bonusWordsFound,
				shuffledLetters: nextProgress.shuffledLetters,
				completedAt: nextProgress.completedAt
					? new Date(nextProgress.completedAt)
					: null,
				lastSyncedAt: new Date(),
			},
		});

	const ackedEventIds = collectAckedEventIds({
		existingEventIds: new Set(
			existingEvents.map((event) => event.clientEventId),
		),
		filteredEvents,
	});

	const previousWordsFound = existingProgress?.guessedWordIds.length ?? 0;
	const previousCompletedAt = existingProgress?.completedAt ?? null;
	const nextCompletedAt = nextProgress.completedAt ?? null;
	const hasProgressDelta = hasLeaderboardScoreDelta(
		{
			wordsFound: previousWordsFound,
			hintsUsed: existingProgress?.hintsUsed ?? 0,
			guessCount: existingProgress?.guessCount ?? 0,
			completed: Boolean(previousCompletedAt),
		},
		{
			wordsFound: nextProgress.guessedWordIds.length,
			hintsUsed: nextProgress.hintsUsed,
			guessCount: nextProgress.guessCount,
			completed: Boolean(nextCompletedAt),
		},
	);

	if (hasProgressDelta) {
		void publishLeaderboardForUser({
			dateKey: puzzleRow.dateKey,
			userId,
			wordsFound: nextProgress.guessedWordIds.length,
			totalWords: privateSnapshot.wordSlots.length,
			freeCluesUsed: nextProgress.hintsUsed,
			tryCount: nextProgress.guessCount,
			completedAt: nextCompletedAt,
			previousWordsFound,
			previousCompletedAt,
		});
	}

	captureServerEvent({
		distinctId: userId,
		event: "puzzle_progress_synced_server",
		properties: {
			acked_event_count: ackedEventIds.length,
			completed: Boolean(nextProgress.completedAt),
			device_id: deviceId,
			guessed_word_count: nextProgress.guessedWordIds.length,
			puzzle_id: puzzleId,
			sanitized_invalid_unlock_token_count:
				diagnostics.sanitizedInvalidUnlockTokenCount,
			sanitized_missing_word_count: diagnostics.sanitizedMissingWordCount,
			received_event_count: events.length,
		},
	});

	return {
		ackedEventIds,
		diagnostics,
		progress: {
			...nextProgress,
			lastSyncedAt: new Date().toISOString(),
		},
	};
}

// Deduplicates by dateKey, preferring full progress over legacy summaries and
// the most recently updated entry among the same source, sorted newest first.
function dedupeHistoryEntriesByDate(
	entries: HistorySummaryEntry[],
): HistorySummaryEntry[] {
	const deduped = new Map<string, HistorySummaryEntry>();
	for (const entry of entries) {
		const existing = deduped.get(entry.dateKey);
		if (!existing) {
			deduped.set(entry.dateKey, entry);
			continue;
		}
		// Prefer non-legacy (full progress) over legacy (summary-only)
		if (!entry.legacy && existing.legacy) {
			deduped.set(entry.dateKey, entry);
			continue;
		}
		// Among same type, prefer more recently updated
		if (entry.lastUpdated > existing.lastUpdated) {
			deduped.set(entry.dateKey, entry);
		}
	}

	return Array.from(deduped.values()).sort((left, right) =>
		right.dateKey.localeCompare(left.dateKey),
	);
}

export async function getHistoryEntriesForUser(userId: string) {
	const progressRows = await db.query.userPuzzleProgress.findMany({
		where: eq(userPuzzleProgress.userId, userId),
		with: {
			puzzle: true,
		},
		orderBy: [desc(userPuzzleProgress.lastSyncedAt)],
	});
	const legacyRows = await db.query.legacyImportedResults.findMany({
		where: eq(legacyImportedResults.userId, userId),
		orderBy: [desc(legacyImportedResults.dateKey)],
	});

	const entries: HistorySummaryEntry[] = progressRows.map((row) => ({
		dateKey: row.puzzle.dateKey,
		seed: row.puzzle.seed,
		totalWords: row.puzzle.wordCount,
		guessedWords: row.guessedWordIds.length,
		guessCount: row.guessCount,
		hintsUsed: row.hintsUsed,
		completed: row.completedAt != null,
		lastUpdated: row.lastSyncedAt.toISOString(),
		difficulty: toPuzzleDifficulty(row.puzzle.difficulty),
	}));

	for (const row of legacyRows) {
		entries.push({
			dateKey: row.dateKey,
			seed: row.seed,
			totalWords: row.totalWords,
			guessedWords: row.guessedWords,
			guessCount: row.guessCount,
			hintsUsed: row.hintsUsed,
			completed: row.completed,
			lastUpdated: row.lastUpdated.toISOString(),
			legacy: true,
		});
	}

	return dedupeHistoryEntriesByDate(entries);
}

// Fetches a single page of detailed history entries ordered newest first. Only
// over-fetches `offset + limit + 1` rows per source table so the initial load
// stays cheap regardless of how many days the account has accumulated. The
// extra row lets us report `hasMore` without a separate count query, and
// over-fetching from both tables keeps the page correct after deduplication
// (the true top-K of the union is always within each table's top-K).
export async function getHistoryEntriesPageForUser(
	userId: string,
	{ offset, limit }: { offset: number; limit: number },
): Promise<HistoryEntriesPage> {
	const fetchCount = offset + limit + 1;

	const progressRows = await db
		.select({
			dateKey: dailyPuzzles.dateKey,
			seed: dailyPuzzles.seed,
			wordCount: dailyPuzzles.wordCount,
			difficulty: dailyPuzzles.difficulty,
			guessedWordIds: userPuzzleProgress.guessedWordIds,
			guessCount: userPuzzleProgress.guessCount,
			hintsUsed: userPuzzleProgress.hintsUsed,
			completedAt: userPuzzleProgress.completedAt,
			lastSyncedAt: userPuzzleProgress.lastSyncedAt,
		})
		.from(userPuzzleProgress)
		.innerJoin(dailyPuzzles, eq(userPuzzleProgress.puzzleId, dailyPuzzles.id))
		.where(eq(userPuzzleProgress.userId, userId))
		.orderBy(desc(dailyPuzzles.dateKey))
		.limit(fetchCount);

	const legacyRows = await db
		.select()
		.from(legacyImportedResults)
		.where(eq(legacyImportedResults.userId, userId))
		.orderBy(desc(legacyImportedResults.dateKey))
		.limit(fetchCount);

	const entries: HistorySummaryEntry[] = progressRows.map((row) => ({
		dateKey: row.dateKey,
		seed: row.seed,
		totalWords: row.wordCount,
		guessedWords: row.guessedWordIds.length,
		guessCount: row.guessCount,
		hintsUsed: row.hintsUsed,
		completed: row.completedAt != null,
		lastUpdated: row.lastSyncedAt.toISOString(),
		difficulty: toPuzzleDifficulty(row.difficulty),
	}));

	for (const row of legacyRows) {
		entries.push({
			dateKey: row.dateKey,
			seed: row.seed,
			totalWords: row.totalWords,
			guessedWords: row.guessedWords,
			guessCount: row.guessCount,
			hintsUsed: row.hintsUsed,
			completed: row.completed,
			lastUpdated: row.lastUpdated.toISOString(),
			legacy: true,
		});
	}

	const deduped = dedupeHistoryEntriesByDate(entries);

	return {
		entries: deduped.slice(offset, offset + limit),
		hasMore: deduped.length > offset + limit,
	};
}

// Computes the aggregate stats independently from the paginated entry list so
// streaks/totals stay accurate without loading every day's heavy columns. Reads
// only the lightweight columns the stats need.
export async function getHistoryStatsForUser(
	userId: string,
): Promise<HistoryStats> {
	const cluesGivenRows = await db
		.select({ cluesGivenCount: user.cluesGivenCount })
		.from(user)
		.where(eq(user.id, userId))
		.limit(1);
	const cluesGiven = cluesGivenRows[0]?.cluesGivenCount ?? 0;

	const progressRows = await db
		.select({
			dateKey: dailyPuzzles.dateKey,
			completedAt: userPuzzleProgress.completedAt,
			guessCount: userPuzzleProgress.guessCount,
			lastSyncedAt: userPuzzleProgress.lastSyncedAt,
		})
		.from(userPuzzleProgress)
		.innerJoin(dailyPuzzles, eq(userPuzzleProgress.puzzleId, dailyPuzzles.id))
		.where(eq(userPuzzleProgress.userId, userId));

	const legacyRows = await db
		.select({
			dateKey: legacyImportedResults.dateKey,
			completed: legacyImportedResults.completed,
			guessCount: legacyImportedResults.guessCount,
			lastUpdated: legacyImportedResults.lastUpdated,
		})
		.from(legacyImportedResults)
		.where(eq(legacyImportedResults.userId, userId));

	const entries: HistorySummaryEntry[] = progressRows.map((row) => ({
		dateKey: row.dateKey,
		seed: null,
		totalWords: 0,
		guessedWords: 0,
		guessCount: row.guessCount,
		hintsUsed: 0,
		completed: row.completedAt != null,
		lastUpdated: row.lastSyncedAt.toISOString(),
	}));

	for (const row of legacyRows) {
		entries.push({
			dateKey: row.dateKey,
			seed: null,
			totalWords: 0,
			guessedWords: 0,
			guessCount: row.guessCount,
			hintsUsed: 0,
			completed: row.completed,
			lastUpdated: row.lastUpdated.toISOString(),
			legacy: true,
		});
	}

	return {
		...calculateHistoryStats(dedupeHistoryEntriesByDate(entries)),
		cluesGiven,
	};
}

// Bumps the lifetime "clues given" counter shown on the profile, called whenever
// a signed-in player successfully answers someone else's clue request. Anonymous
// responders have no user row to credit, so callers only invoke this for known
// users (see handleRespond).
export async function incrementCluesGivenCount(userId: string): Promise<void> {
	await db
		.update(user)
		.set({ cluesGivenCount: sql`${user.cluesGivenCount} + 1` })
		.where(eq(user.id, userId));
}

export type AccountHistoryPage = HistoryEntriesPage & {
	stats: HistoryStats;
};

export async function getHistoryPageDataForUser(
	userId?: string,
	dateKey = getYesterdayDateKey(),
) {
	// Read-only: the date reaches here from a request, and a day nobody played
	// has no stored puzzle. Generating one on the spot would let any caller fill
	// the table with puzzles for arbitrary past dates, so the panel is simply
	// omitted instead (see yesterdayPuzzle below).
	const yesterdayPuzzleRow = await readDailyPuzzleRow(dateKey);
	const accountHistory: AccountHistoryPage | null = userId
		? {
				...(await getHistoryEntriesPageForUser(userId, {
					offset: 0,
					limit: HISTORY_PAGE_SIZE,
				})),
				stats: await getHistoryStatsForUser(userId),
			}
		: null;
	const yesterdayLeaderboard = await getLeaderboard(dateKey);

	captureServerEvent({
		distinctId: userId,
		event: "history_page_loaded_server",
		properties: {
			date_key: dateKey,
			has_account_history: Boolean(accountHistory),
			history_entry_count: accountHistory?.stats.totalDays ?? 0,
			yesterday_leaderboard_entry_count: yesterdayLeaderboard.entries.length,
		},
	});

	return {
		accountHistory,
		yesterdayPuzzle: yesterdayPuzzleRow
			? {
					dateKey: yesterdayPuzzleRow.dateKey,
					preview: toPuzzlePreview(yesterdayPuzzleRow.privateSnapshotJson),
					difficulty: toPuzzleDifficulty(
						yesterdayPuzzleRow.difficulty ??
							yesterdayPuzzleRow.publicSnapshotJson.difficulty,
					),
				}
			: null,
		yesterdayLeaderboard,
	};
}

export async function importAnonymousProgressForUser(options: {
	userId: string;
	// The guest's server-issued leaderboard identity, read from the signed
	// cookie. Null when this browser never played as a guest, in which case
	// there is no anonymous board entry to merge in.
	anonDeviceId: string | null;
	payload: AnonymousImportPayload;
}) {
	const { anonDeviceId, payload, userId } = options;
	const importedDates: string[] = [];
	const skippedLegacyDates: string[] = [];
	const importedForLeaderboard: Array<{
		dateKey: string;
		wordsFound: number;
		totalWords: number;
		freeCluesUsed: number;
		tryCount: number;
		completedAt: string | null;
	}> = [];

	for (const historyEntry of payload.historyEntries) {
		const activeProgress = payload.activeProgressByDate[historyEntry.dateKey];
		if (!activeProgress) {
			await db
				.insert(legacyImportedResults)
				.values({
					id: crypto.randomUUID(),
					userId,
					dateKey: historyEntry.dateKey,
					seed: historyEntry.seed,
					totalWords: historyEntry.totalWords,
					guessedWords: historyEntry.guessedWords,
					guessCount: historyEntry.guessCount,
					hintsUsed: historyEntry.hintsUsed,
					completed: historyEntry.completed,
					lastUpdated: new Date(historyEntry.lastUpdated),
				})
				.onConflictDoUpdate({
					target: [legacyImportedResults.userId, legacyImportedResults.dateKey],
					set: {
						seed: historyEntry.seed,
						totalWords: historyEntry.totalWords,
						guessedWords: historyEntry.guessedWords,
						guessCount: historyEntry.guessCount,
						hintsUsed: historyEntry.hintsUsed,
						completed: historyEntry.completed,
						lastUpdated: new Date(historyEntry.lastUpdated),
					},
				});
			skippedLegacyDates.push(historyEntry.dateKey);
			continue;
		}

		// Read-only: these date keys come straight from the client's localStorage
		// payload, so generating here would let any signed-in account create
		// puzzles for arbitrary dates. A day with no stored puzzle is imported as
		// a legacy result, the same fallback used when the progress doesn't match.
		const puzzle = await readDailyPuzzleRow(historyEntry.dateKey);
		if (
			!puzzle ||
			!getCompatibleProgress(activeProgress, puzzle.publicSnapshotJson)
		) {
			await db
				.insert(legacyImportedResults)
				.values({
					id: crypto.randomUUID(),
					userId,
					dateKey: historyEntry.dateKey,
					seed: historyEntry.seed,
					totalWords: historyEntry.totalWords,
					guessedWords: historyEntry.guessedWords,
					guessCount: historyEntry.guessCount,
					hintsUsed: historyEntry.hintsUsed,
					completed: historyEntry.completed,
					lastUpdated: new Date(historyEntry.lastUpdated),
				})
				.onConflictDoUpdate({
					target: [legacyImportedResults.userId, legacyImportedResults.dateKey],
					set: {
						seed: historyEntry.seed,
						totalWords: historyEntry.totalWords,
						guessedWords: historyEntry.guessedWords,
						guessCount: historyEntry.guessCount,
						hintsUsed: historyEntry.hintsUsed,
						completed: historyEntry.completed,
						lastUpdated: new Date(historyEntry.lastUpdated),
					},
				});
			skippedLegacyDates.push(historyEntry.dateKey);
			continue;
		}

		const existingProgress = await getUserPuzzleProgressData(puzzle.id, userId);
		const merged = mergeProgressStates(existingProgress, activeProgress);

		await db
			.insert(userPuzzleProgress)
			.values({
				id: `${userId}:${puzzle.id}`,
				userId,
				puzzleId: puzzle.id,
				guessHashes: merged.guessHashes,
				guessedWordIds: merged.guessedWordIds,
				revealedWordTokens: merged.revealedWordTokens,
				hintedCells: merged.hintedCells,
				hintsUsed: merged.hintsUsed,
				guessCount: merged.guessCount,
				bonusWordsFound: merged.bonusWordsFound,
				shuffledLetters: merged.shuffledLetters,
				completedAt: merged.completedAt ? new Date(merged.completedAt) : null,
				lastSyncedAt: new Date(),
			})
			.onConflictDoUpdate({
				target: userPuzzleProgress.id,
				set: {
					guessHashes: merged.guessHashes,
					guessedWordIds: merged.guessedWordIds,
					revealedWordTokens: merged.revealedWordTokens,
					hintedCells: merged.hintedCells,
					hintsUsed: merged.hintsUsed,
					guessCount: merged.guessCount,
					bonusWordsFound: merged.bonusWordsFound,
					shuffledLetters: merged.shuffledLetters,
					completedAt: merged.completedAt ? new Date(merged.completedAt) : null,
					lastSyncedAt: new Date(),
				},
			});

		importedDates.push(historyEntry.dateKey);
		importedForLeaderboard.push({
			dateKey: historyEntry.dateKey,
			wordsFound: merged.guessedWordIds.length,
			totalWords: puzzle.privateSnapshotJson.wordSlots.length,
			freeCluesUsed: merged.hintsUsed,
			tryCount: merged.guessCount,
			completedAt: merged.completedAt,
		});
	}

	const dateKeysForLeaderboardMerge = [
		getTodayDateKey(),
		...importedDates,
		...skippedLegacyDates,
		...Object.keys(payload.activeProgressByDate),
		...payload.historyEntries.map((entry) => entry.dateKey),
	];

	try {
		const profiles = await db
			.select({
				name: user.name,
				displayName: user.displayName,
				image: user.image,
				useGoogleAvatar: user.useGoogleAvatar,
			})
			.from(user)
			.where(eq(user.id, userId))
			.limit(1);
		const profile = profiles[0];
		if (profile && anonDeviceId) {
			await mergeAnonLeaderboardForUser({
				deviceId: anonDeviceId,
				userId,
				name: resolveDisplayName(profile),
				image: resolveAvatarImage(profile),
				dateKeys: dateKeysForLeaderboardMerge,
			});
		}
	} catch (error) {
		console.warn("[leaderboard] merge anon on import failed", error);
	}

	for (const imported of importedForLeaderboard) {
		if (imported.wordsFound === 0 && !imported.completedAt) {
			continue;
		}
		try {
			await publishLeaderboardForUser({
				dateKey: imported.dateKey,
				userId,
				wordsFound: imported.wordsFound,
				totalWords: imported.totalWords,
				freeCluesUsed: imported.freeCluesUsed,
				tryCount: imported.tryCount,
				completedAt: imported.completedAt,
				previousWordsFound: 0,
				previousCompletedAt: null,
			});
		} catch (error) {
			console.warn("[leaderboard] publish on import failed", error);
		}
	}

	captureServerEvent({
		distinctId: userId,
		event: "anonymous_progress_imported_server",
		properties: {
			active_progress_count: Object.keys(payload.activeProgressByDate).length,
			imported_dates: importedDates.length,
			legacy_dates: skippedLegacyDates.length,
			merged_leaderboard_dates: dateKeysForLeaderboardMerge.length,
		},
	});

	return {
		importedDates,
		skippedLegacyDates,
	};
}

export async function updateUserProfileData(input: {
	userId: string;
	displayName?: string;
	useGoogleAvatar?: boolean;
}) {
	const normalizedName =
		input.displayName === undefined
			? undefined
			: normalizeDisplayNameInput(input.displayName);

	if (input.displayName !== undefined && normalizedName === null) {
		throw new Error("Invalid display name");
	}

	const updates: {
		displayName?: string | null;
		useGoogleAvatar?: boolean;
	} = {};

	if (normalizedName !== undefined) {
		const profiles = await db
			.select({ name: user.name })
			.from(user)
			.where(eq(user.id, input.userId))
			.limit(1);
		const oauthName = profiles[0]?.name.trim();
		const normalizedOauthName =
			(oauthName ? normalizeDisplayNameInput(oauthName) : null) ?? oauthName;
		updates.displayName =
			normalizedName && normalizedName !== normalizedOauthName
				? normalizedName
				: null;
	}

	if (input.useGoogleAvatar !== undefined) {
		updates.useGoogleAvatar = input.useGoogleAvatar;
	}

	if (Object.keys(updates).length === 0) {
		const profile = await db
			.select({
				name: user.name,
				displayName: user.displayName,
				image: user.image,
				useGoogleAvatar: user.useGoogleAvatar,
			})
			.from(user)
			.where(eq(user.id, input.userId))
			.limit(1);
		const saved = profile[0];
		if (!saved) {
			throw new Error("User not found");
		}
		return {
			displayName: saved.displayName,
			useGoogleAvatar: saved.useGoogleAvatar,
			name: resolveDisplayName(saved),
			image: resolveAvatarImage(saved),
		};
	}

	await db.update(user).set(updates).where(eq(user.id, input.userId));

	const profile = await db
		.select({
			name: user.name,
			displayName: user.displayName,
			image: user.image,
			useGoogleAvatar: user.useGoogleAvatar,
		})
		.from(user)
		.where(eq(user.id, input.userId))
		.limit(1);
	const saved = profile[0];
	if (!saved) {
		throw new Error("User not found");
	}

	try {
		await updateLeaderboardProfile({
			dateKey: getTodayDateKey(),
			participantId: userParticipantId(input.userId),
			name: leaderboardDisplayName(resolveDisplayName(saved)),
			image: resolveAvatarImage(saved),
		});
	} catch (error) {
		console.warn("[leaderboard] profile refresh failed", error);
	}

	return {
		displayName: saved.displayName,
		useGoogleAvatar: saved.useGoogleAvatar,
		name: resolveDisplayName(saved),
		image: resolveAvatarImage(saved),
	};
}

export async function decodeRevealedWords(
	puzzle: DailyPuzzlePublic,
	progress: PuzzleProgressState,
) {
	const entries = await Promise.all(
		puzzle.wordSlots
			.filter((slot) => progress.guessedWordIds.includes(slot.id))
			.map(async (slot) => {
				const unlockToken = progress.revealedWordTokens[String(slot.id)];
				if (!unlockToken) return null;
				return [
					slot.id,
					await openAnswerCapsule(slot.answerCapsule, unlockToken),
				] as const;
			}),
	);

	return Object.fromEntries(
		entries.filter(Boolean) as Array<readonly [number, string]>,
	);
}
