stages:
  - check
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: "true"

sast:
  stage: check

secret_detection:
  stage: check

lint:
  stage: check
  image: node:25.2-slim
  before_script:
    - npm install -g pnpm@latest-10
    - pnpm install
  script:
    - pnpm lint
    - pnpm check
    - pnpm typecheck
  cache:
    paths:
      - node_modules

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client sshpass
  script:
    - chmod +x scripts/deploy.sh
    - scripts/deploy.sh
  only:
    - main
