/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreferenciesRouteImport } from './routes/preferencies'
import { Route as DiesAnteriorsRouteImport } from './routes/dies-anteriors'
import { Route as ClassificacioRouteImport } from './routes/classificacio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhSplatRouteImport } from './routes/ph/$'
import { Route as ApiLeaderboardSplatRouteImport } from './routes/api/leaderboard/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PreferenciesRoute = PreferenciesRouteImport.update({
  id: '/preferencies',
  path: '/preferencies',
  getParentRoute: () => rootRouteImport,
} as any)
const DiesAnteriorsRoute = DiesAnteriorsRouteImport.update({
  id: '/dies-anteriors',
  path: '/dies-anteriors',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacioRoute = ClassificacioRouteImport.update({
  id: '/classificacio',
  path: '/classificacio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhSplatRoute = PhSplatRouteImport.update({
  id: '/ph/$',
  path: '/ph/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardSplatRoute = ApiLeaderboardSplatRouteImport.update({
  id: '/api/leaderboard/$',
  path: '/api/leaderboard/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classificacio': typeof ClassificacioRoute
  '/dies-anteriors': typeof DiesAnteriorsRoute
  '/preferencies': typeof PreferenciesRoute
  '/ph/$': typeof PhSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/leaderboard/$': typeof ApiLeaderboardSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classificacio': typeof ClassificacioRoute
  '/dies-anteriors': typeof DiesAnteriorsRoute
  '/preferencies': typeof PreferenciesRoute
  '/ph/$': typeof PhSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/leaderboard/$': typeof ApiLeaderboardSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classificacio': typeof ClassificacioRoute
  '/dies-anteriors': typeof DiesAnteriorsRoute
  '/preferencies': typeof PreferenciesRoute
  '/ph/$': typeof PhSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/leaderboard/$': typeof ApiLeaderboardSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classificacio'
    | '/dies-anteriors'
    | '/preferencies'
    | '/ph/$'
    | '/api/auth/$'
    | '/api/leaderboard/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classificacio'
    | '/dies-anteriors'
    | '/preferencies'
    | '/ph/$'
    | '/api/auth/$'
    | '/api/leaderboard/$'
  id:
    | '__root__'
    | '/'
    | '/classificacio'
    | '/dies-anteriors'
    | '/preferencies'
    | '/ph/$'
    | '/api/auth/$'
    | '/api/leaderboard/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassificacioRoute: typeof ClassificacioRoute
  DiesAnteriorsRoute: typeof DiesAnteriorsRoute
  PreferenciesRoute: typeof PreferenciesRoute
  PhSplatRoute: typeof PhSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLeaderboardSplatRoute: typeof ApiLeaderboardSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preferencies': {
      id: '/preferencies'
      path: '/preferencies'
      fullPath: '/preferencies'
      preLoaderRoute: typeof PreferenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dies-anteriors': {
      id: '/dies-anteriors'
      path: '/dies-anteriors'
      fullPath: '/dies-anteriors'
      preLoaderRoute: typeof DiesAnteriorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacio': {
      id: '/classificacio'
      path: '/classificacio'
      fullPath: '/classificacio'
      preLoaderRoute: typeof ClassificacioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ph/$': {
      id: '/ph/$'
      path: '/ph/$'
      fullPath: '/ph/$'
      preLoaderRoute: typeof PhSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard/$': {
      id: '/api/leaderboard/$'
      path: '/api/leaderboard/$'
      fullPath: '/api/leaderboard/$'
      preLoaderRoute: typeof ApiLeaderboardSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassificacioRoute: ClassificacioRoute,
  DiesAnteriorsRoute: DiesAnteriorsRoute,
  PreferenciesRoute: PreferenciesRoute,
  PhSplatRoute: PhSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLeaderboardSplatRoute: ApiLeaderboardSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
