/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassificacioRouteImport } from './routes/classificacio'
import { Route as DiesAnteriorsRouteImport } from './routes/dies-anteriors'
import { Route as PreferenciesRouteImport } from './routes/preferencies'
import { Route as SobreElJocRouteImport } from './routes/sobre-el-joc'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMonitoringRouteImport } from './routes/api/monitoring'
import { Route as ApiURouteImport } from './routes/api/u'
import { Route as MiniIndexRouteImport } from './routes/mini.index'
import { Route as MiniDiesAnteriorsRouteImport } from './routes/mini.dies-anteriors'
import { Route as PhSplatRouteImport } from './routes/ph/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiClueRequestsSplatRouteImport } from './routes/api/clue-requests/$'
import { Route as ApiLeaderboardSplatRouteImport } from './routes/api/leaderboard/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacioRoute = ClassificacioRouteImport.update({
  id: '/classificacio',
  path: '/classificacio',
  getParentRoute: () => rootRouteImport,
} as any)
const DiesAnteriorsRoute = DiesAnteriorsRouteImport.update({
  id: '/dies-anteriors',
  path: '/dies-anteriors',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferenciesRoute = PreferenciesRouteImport.update({
  id: '/preferencies',
  path: '/preferencies',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreElJocRoute = SobreElJocRouteImport.update({
  id: '/sobre-el-joc',
  path: '/sobre-el-joc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitoringRoute = ApiMonitoringRouteImport.update({
  id: '/api/monitoring',
  path: '/api/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiURoute = ApiURouteImport.update({
  id: '/api/u',
  path: '/api/u',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniIndexRoute = MiniIndexRouteImport.update({
  id: '/mini/',
  path: '/mini/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniDiesAnteriorsRoute = MiniDiesAnteriorsRouteImport.update({
  id: '/mini/dies-anteriors',
  path: '/mini/dies-anteriors',
  getParentRoute: () => rootRouteImport,
} as any)
const PhSplatRoute = PhSplatRouteImport.update({
  id: '/ph/$',
  path: '/ph/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClueRequestsSplatRoute = ApiClueRequestsSplatRouteImport.update({
  id: '/api/clue-requests/$',
  path: '/api/clue-requests/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardSplatRoute = ApiLeaderboardSplatRouteImport.update({
  id: '/api/leaderboard/$',
  path: '/api/leaderboard/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classificacio': typeof ClassificacioRoute
  '/dies-anteriors': typeof DiesAnteriorsRoute
  '/preferencies': typeof PreferenciesRoute
  '/sobre-el-joc': typeof SobreElJocRoute
  '/api/health': typeof ApiHealthRoute
  '/api/monitoring': typeof ApiMonitoringRoute
  '/api/u': typeof ApiURoute
  '/mini/dies-anteriors': typeof MiniDiesAnteriorsRoute
  '/ph/$': typeof PhSplatRoute
  '/mini/': typeof MiniIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/clue-requests/$': typeof ApiClueRequestsSplatRoute
  '/api/leaderboard/$': typeof ApiLeaderboardSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classificacio': typeof ClassificacioRoute
  '/dies-anteriors': typeof DiesAnteriorsRoute
  '/preferencies': typeof PreferenciesRoute
  '/sobre-el-joc': typeof SobreElJocRoute
  '/api/health': typeof ApiHealthRoute
  '/api/monitoring': typeof ApiMonitoringRoute
  '/api/u': typeof ApiURoute
  '/mini/dies-anteriors': typeof MiniDiesAnteriorsRoute
  '/ph/$': typeof PhSplatRoute
  '/mini': typeof MiniIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/clue-requests/$': typeof ApiClueRequestsSplatRoute
  '/api/leaderboard/$': typeof ApiLeaderboardSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classificacio': typeof ClassificacioRoute
  '/dies-anteriors': typeof DiesAnteriorsRoute
  '/preferencies': typeof PreferenciesRoute
  '/sobre-el-joc': typeof SobreElJocRoute
  '/api/health': typeof ApiHealthRoute
  '/api/monitoring': typeof ApiMonitoringRoute
  '/api/u': typeof ApiURoute
  '/mini/dies-anteriors': typeof MiniDiesAnteriorsRoute
  '/ph/$': typeof PhSplatRoute
  '/mini/': typeof MiniIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/clue-requests/$': typeof ApiClueRequestsSplatRoute
  '/api/leaderboard/$': typeof ApiLeaderboardSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classificacio'
    | '/dies-anteriors'
    | '/preferencies'
    | '/sobre-el-joc'
    | '/api/health'
    | '/api/monitoring'
    | '/api/u'
    | '/mini/dies-anteriors'
    | '/ph/$'
    | '/mini/'
    | '/api/auth/$'
    | '/api/clue-requests/$'
    | '/api/leaderboard/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classificacio'
    | '/dies-anteriors'
    | '/preferencies'
    | '/sobre-el-joc'
    | '/api/health'
    | '/api/monitoring'
    | '/api/u'
    | '/mini/dies-anteriors'
    | '/ph/$'
    | '/mini'
    | '/api/auth/$'
    | '/api/clue-requests/$'
    | '/api/leaderboard/$'
  id:
    | '__root__'
    | '/'
    | '/classificacio'
    | '/dies-anteriors'
    | '/preferencies'
    | '/sobre-el-joc'
    | '/api/health'
    | '/api/monitoring'
    | '/api/u'
    | '/mini/dies-anteriors'
    | '/ph/$'
    | '/mini/'
    | '/api/auth/$'
    | '/api/clue-requests/$'
    | '/api/leaderboard/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassificacioRoute: typeof ClassificacioRoute
  DiesAnteriorsRoute: typeof DiesAnteriorsRoute
  PreferenciesRoute: typeof PreferenciesRoute
  SobreElJocRoute: typeof SobreElJocRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMonitoringRoute: typeof ApiMonitoringRoute
  ApiURoute: typeof ApiURoute
  MiniDiesAnteriorsRoute: typeof MiniDiesAnteriorsRoute
  PhSplatRoute: typeof PhSplatRoute
  MiniIndexRoute: typeof MiniIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiClueRequestsSplatRoute: typeof ApiClueRequestsSplatRoute
  ApiLeaderboardSplatRoute: typeof ApiLeaderboardSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacio': {
      id: '/classificacio'
      path: '/classificacio'
      fullPath: '/classificacio'
      preLoaderRoute: typeof ClassificacioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dies-anteriors': {
      id: '/dies-anteriors'
      path: '/dies-anteriors'
      fullPath: '/dies-anteriors'
      preLoaderRoute: typeof DiesAnteriorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferencies': {
      id: '/preferencies'
      path: '/preferencies'
      fullPath: '/preferencies'
      preLoaderRoute: typeof PreferenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-el-joc': {
      id: '/sobre-el-joc'
      path: '/sobre-el-joc'
      fullPath: '/sobre-el-joc'
      preLoaderRoute: typeof SobreElJocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitoring': {
      id: '/api/monitoring'
      path: '/api/monitoring'
      fullPath: '/api/monitoring'
      preLoaderRoute: typeof ApiMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/u': {
      id: '/api/u'
      path: '/api/u'
      fullPath: '/api/u'
      preLoaderRoute: typeof ApiURouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini/': {
      id: '/mini/'
      path: '/mini'
      fullPath: '/mini/'
      preLoaderRoute: typeof MiniIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini/dies-anteriors': {
      id: '/mini/dies-anteriors'
      path: '/mini/dies-anteriors'
      fullPath: '/mini/dies-anteriors'
      preLoaderRoute: typeof MiniDiesAnteriorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ph/$': {
      id: '/ph/$'
      path: '/ph/$'
      fullPath: '/ph/$'
      preLoaderRoute: typeof PhSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clue-requests/$': {
      id: '/api/clue-requests/$'
      path: '/api/clue-requests/$'
      fullPath: '/api/clue-requests/$'
      preLoaderRoute: typeof ApiClueRequestsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard/$': {
      id: '/api/leaderboard/$'
      path: '/api/leaderboard/$'
      fullPath: '/api/leaderboard/$'
      preLoaderRoute: typeof ApiLeaderboardSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassificacioRoute: ClassificacioRoute,
  DiesAnteriorsRoute: DiesAnteriorsRoute,
  PreferenciesRoute: PreferenciesRoute,
  SobreElJocRoute: SobreElJocRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMonitoringRoute: ApiMonitoringRoute,
  ApiURoute: ApiURoute,
  MiniDiesAnteriorsRoute: MiniDiesAnteriorsRoute,
  PhSplatRoute: PhSplatRoute,
  MiniIndexRoute: MiniIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiClueRequestsSplatRoute: ApiClueRequestsSplatRoute,
  ApiLeaderboardSplatRoute: ApiLeaderboardSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
